### ISSUE TITLE
PyPop 1.0.0b3 does not work on M1 Mac

### ISSUE THREAD

**Issue by odoublewen** [alexlancaster/pypop#142]
**Describe the bug**
When running the test example files on an M1 (aka Apple Silicon, aka ARM architecture) Mac , PyPop thows an error.

```
$ pypop -c  minimal.ini USAFEL-UchiTelle-small.pop 
Traceback (most recent call last):
  File "/Users/owen/temp/venv/bin/pypop", line 8, in <module>
    sys.exit(main())
  File "/Users/owen/temp/venv/lib/python3.10/site-packages/PyPop/pypop.py", line 261, in main
    application = Main(config=config,
  File "/Users/owen/temp/venv/lib/python3.10/site-packages/PyPop/Main.py", line 415, in __init__
    self._doGenotypeFile()
  File "/Users/owen/temp/venv/lib/python3.10/site-packages/PyPop/Main.py", line 757, in _doGenotypeFile
    hwObject.dumpTable(locus, self.xmlStream)
  File "/Users/owen/temp/venv/lib/python3.10/site-packages/PyPop/HardyWeinberg.py", line 856, in dumpTable
    from PyPop import _Gthwe
ImportError: dlopen(/Users/owen/temp/venv/lib/python3.10/site-packages/PyPop/_Gthwe.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (_gsl_rng_default)
```

**Desktop (please complete the following information):**
 - OS: MacOS 12.6.7
 - Version: pypop 1.0.0b3

**Additional context**
See attached file showing verbose install log and error:  [log.txt](https://github.com/alexlancaster/pypop/files/12887957/log.txt)

**Comment by alexlancaster** [comment]
> **Describe the bug** When running the test example files on an M1 (aka Apple Silicon, aka ARM architecture) Mac , PyPop thows an error.
> 
> ```
> $ pypop -c  minimal.ini USAFEL-UchiTelle-small.pop 
> Traceback (most recent call last):
>   File "/Users/owen/temp/venv/bin/pypop", line 8, in <module>
>     sys.exit(main())
>   File "/Users/owen/temp/venv/lib/python3.10/site-packages/PyPop/pypop.py", line 261, in main
>     application = Main(config=config,
>   File "/Users/owen/temp/venv/lib/python3.10/site-packages/PyPop/Main.py", line 415, in __init__
>     self._doGenotypeFile()
>   File "/Users/owen/temp/venv/lib/python3.10/site-packages/PyPop/Main.py", line 757, in _doGenotypeFile
>     hwObject.dumpTable(locus, self.xmlStream)
>   File "/Users/owen/temp/venv/lib/python3.10/site-packages/PyPop/HardyWeinberg.py", line 856, in dumpTable
>     from PyPop import _Gthwe
> ImportError: dlopen(/Users/owen/temp/venv/lib/python3.10/site-packages/PyPop/_Gthwe.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (_gsl_rng_default)
> ```

Thanks again for the report.  Proximate cause of the crash is that it can't find the shared library for `gsl` in the package.  This is because during the `cibuildwheel` on the runner, we use `brew install gsl` to install the `gsl` package - but because it's done as a cross-compilation on a x86, it installs the x86 version of `gsl`.  This means that although the compilation succeeds, it does not include the `gsl` library in the `pypop-genomics` package during the "repair wheel" stage, and thus fails at run-time.

I reworked the `pyproject.toml` to force `brew` to install the `arm64` version of the package and now it seems to package it.  I built a test wheel, can you download it here: 
[arm64-artifact.zip](https://github.com/alexlancaster/pypop/files/12890017/arm64-artifact.zip)

and then test it:

```
unzip arm64-artifact.zip
pip install -U pypop_genomics-1.0.0b3.post10+g630a10a-cp310-cp310-macosx_11_0_arm64.whl
```
If that works, I'll have to ensure that the install works properly on the x86_64 platform too.

**Comment by odoublewen** [comment]
Yes, it now works!

**Comment by alexlancaster** [comment]
> Yes, it now works!

great! new 1.0.0b4 release up with the arm64 fix on PyPI!  https://pypi.org/project/pypop-genomics/
