### ISSUE TITLE
allele drop out - question

### ISSUE THREAD

**Issue by kosoegawa** [alexlancaster/pypop#23]
Marcelo asked:
Do you have a standard way to represent locus that had failure, "dropout" in the new version of the software? Just leaving as empty would work? Every HLA typing software has different way of reporting dropout. MiaFora software reports as "Insufficient data".

**Comment by sjmack** [comment]
This would be "missing" data, which can be defined in the [ParseGenotypeFile] section of the .ini (config) file as an "untyped Allele". In other programs this is defined as "NA" or "N/A".
 
```
[ParseGenotypeFile]
untypedAllele=****
```

"****" is the default value, but the .ini can be modified to use a different value. 

TTBOMK, PyPop ignores these untyped alleles, and they are not included in calculations or tests. This means that, "****" should not be used to denote a structural variant (like the absence of a DRB3 allele). These can be noted with their own value, which will be treated as a variant, since they are nucleotide variants (very large deletions). For example, we use "00:00" to denote the absence of a locus.

**Comment by alexlancaster** [comment]
Hi Kazu, yes the way we deal with this currently in PyPop is as Steve describes it above.  In principle this can be set to any character, but we want to avoid the tilde character as that is what we use internally to separate genotypes.  It can be set to "N/A" or "NA" if desired as well.

Also, again as Steve mentioned, you only want to use the untyped allele if there is literally missing data, not if it represents something else.

**Comment by alexlancaster** [comment]
Hi @kosoegawa does this fix/address your issue?  If so, go ahead and close, or I can do it if you like.
