### ISSUE TITLE
ambiguous haplotypes 

### ISSUE THREAD

**Issue by afadda91** [alexlancaster/pypop#48]
Hello again,
I'm wondering if Pypop deals with ambiguity represented in a slash between types. From the results it looks like it teats them as one unit, i.e. one new type. Please advise.
thanks,

**Comment by sjmack** [comment]
@afadda91, you are correct. Slash-delimited ambiguities are not currently resolved by PyPop. 

I think we would like to be able to build in some support for disambiguation/ambiguity resolution in a future version of PyPop, but that is still a ways off. 

Ideally, you could use a custom binning filter (see the CustomBinning Block in this [example config file](http://pypop.org/popdata/2008/config-allelecount.ini) to change all ambiguities of a given type to a specific allele (or to the same ambiguity, or a G group, etc.), based on your own assumptions about what an ambiguous string should be resolved to. To make this work, because the custom binning filter uses slashes to delimit possible alleles, you would have to use a different delimiter to identify the separate alleles in your strings (e.g., ".", as below). However, as you will see in issue #43, the CustomBinning filters are not working with the Master Branch of this repo (version 0.8.0). 

You **can** successfully use CustomBinning with [PyPop version 0.7.0](https://github.com/alexlancaster/pypop/tree/3f29d4b53548ce4deb60a5960368627999396653), but remember that version 0.7.0 does not support colon-delimited allele names.

So here is an example: If I have HLA-A data that is ambiguous as below (with . instead of /):

```
 populat	id	a_1	a_2	
 test	test001	0201.0202.0203	1101.1102.1103
 test	test002	0201.0202.0203.0204	1103.1104.1105
```
I can add the following to my .ini

```
 [Filters] 
 filtersToApply=CustomBinning

 [CustomBinning]
 A=!0201/0201.0202.0203/0201.0202.0203.0204
 !1101/1101.1102.1103/1103.1104.1105
```

All of the ambiguous alleles reported as "0201.0202.0203" or "0201.0202.0203.0204" will be converted to "0201" and all of the ambiguous alleles reported as "1101.1102.1103" or "1103.1104.1105" will be converted to "1101". 

This results in an additional file called "pop_file-filter.xml" being generated as part of the PyPop results. This file documents all of the changes made to your .pop data by PyPop as it reads your data through the filter. By reviewing this file, you can ensure that your filter is behaving appropriately. 

The pop_file-filter.xml file will contain messages like this:

```
Exact rule match: A* 0201.0202.0203 is being replaced by 0201 
Exact rule match: A* 1101.1102.1103 is being replaced by 1101 
Exact rule match: A* 0201.0202.0203.0204 is being replaced by 0201 
Exact rule match: A* 1103.1104.1105 is being replaced by 1101 
```

Of course, you need to determine how you want PyPop to interpret your ambiguous strings, when you make your Custom Binning rules.

Happy New Year!
